#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <ithasu_rainbow_icons.h>

#include "led_driver.h"

const int led_count = 8;
const GpioPin* const pin_led = &gpio_swclk;
const GpioPin* const pin_back = &gpio_button_back;

int32_t ithasu_rainbow_app(void* p) {
    UNUSED(p);

    // -- Init LED driver -----------------------------------------------------
    LedDriver* driver = led_driver_alloc(led_count, pin_led);

    // -- Rainbow !! ----------------------------------------------------------
    size_t offset = 0;
    // Loop until back button is pressed
    while(furi_hal_gpio_read(pin_back)) {
        for(size_t i = 0; i < led_count; i++) {
            uint32_t color = 0x000000;
            if(((i + offset) & 0x01) != 0) {
                color |= 0x100000;
            }
            if(((i + offset) & 0x02) != 0) {
                color |= 0x001000;
            }
            if(((i + offset) & 0x04) != 0) {
                color |= 0x000010;
            }
            led_driver_set_led(driver, i, color);
        }

        // Wait for next step
        offset++;
        furi_delay_ms(100);
        led_driver_transmit(driver, true);
    }

    // -- Power off -----------------------------------------------------------
    for(size_t i = 0; i < 24; i++) {
        led_driver_set_led(driver, i, 0x000000);
    }
    led_driver_transmit(driver, true);

    // -- Free ----------------------------------------------------------------
    led_driver_free(driver);

    return 0;
}
